swagger: "2.0"
info:
  version: "1.0.0"
  title: "gpt2-covidArticle"
host: "master-gpt2-covid-article-ha-mulan.endpoint.ainize.ai"
basePath: "/api/"
schemes:
- "https"
- "http"
consumes:
  - string
produces:
  - string
paths:
  /:
    get:
      tags:
      - "generate covid article base on keyword"
      summary: "generate covid article base on keyword"
      description: 'please input keyword of covid article.

      This app is generate covid article in text form.


      How to use:
        
        First, input keyword related to covid-19.

        Second, wait for result.


      '
      produces:
      - "string"
      - "application/xml"
      - "application/json"
      parameters:
      - name: "keyword"
        type: 'string'
        in: "query"
        description: "ex) type 'deadly'"
        required: true
        items:
          type: "string"
          default: "trump"
      responses:
        "200":
          description: "successful operation"
        "400":
          description: "Invalid status value"

externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
